services:
  anvil:
    image: ghcr.io/foundry-rs/foundry@sha256:805788a91fa2c5868dfbdab17f311e3267777cfaaf2fafe22905ff7e96c8d8ec
    ports: ['8545:8545']
    entrypoint:
      ['anvil', '--host', '0.0.0.0', '--silent', '--hardfork', 'prague']
    platform: linux/amd64
    healthcheck:
      test:
        [
          'CMD-SHELL',
          'cast rpc web3_clientVersion | grep -c anvil > /dev/null ',
        ]
      start_interval: 250ms
      start_period: 10s
      interval: 30s
      timeout: 5s
      retries: 50
  contract-deployer:
    image: ghcr.io/pimlicolabs/mock-contract-deployer@sha256:50207a6b6c529c572f9928ff0179fce16f4246cbff3c863b91434af586a544b9
    environment:
      - ANVIL_RPC=http://anvil:8545
    depends_on:
      anvil:
        condition: service_healthy
  mock-paymaster:
    image: ghcr.io/pimlicolabs/mock-verifying-paymaster@sha256:588629c066e5060635ac9756679b8d9049eeb412003cd96a518944dccd0b3b01
    ports: ['3000:3000']
    environment:
      - ALTO_RPC=http://alto:4337
      - ANVIL_RPC=http://anvil:8545

  alto:
    build: https://github.com/pimlicolabs/alto.git#v1.2.5
    ports: ['4337:4337']
    environment:
      - ANVIL_RPC=http://anvil:8545
    depends_on:
      anvil:
        condition: service_healthy
      contract-deployer:
        condition: service_completed_successfully
    volumes:
      - ./alto-config.json:/app/alto-config.json
    entrypoint:
      [
        'node',
        'src/lib/cli/alto.js',
        'run',
        '--config',
        '/app/alto-config.json',
      ]
